name: flare-rpg
version: '1.12'
summary: An open source, 2D action RPG
description: |
  The Flare Engine with The Empyrean Campaign
  .
  The story begins with the player being exiled from their homeland of Empyrean,
  resulting in them embarking on a quest to regain entry. This journey takes the
  player through many regions, with plenty of side quests along the way.
grade: stable
confinement: strict
base: core20
compression: lzo

apps:
  flare-rpg:
    command: $SNAP/usr/games/flare --data-path $SNAP
    plugs: [ unity7, joystick, pulseaudio, opengl ]
    extensions: [gnome-3-38]

parts:
  engine:
    plugin: cmake
    source: https://github.com/flareteam/flare-engine.git
    source-tag: v1.12
    cmake-parameters: [ -DCMAKE_INSTALL_PREFIX=/usr ]
    build-packages:
      - make
      - cmake
      - g++
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libsdl2-mixer-2.0-0
      - libsdl2-ttf-2.0-0
      - libgl1-mesa-glx
    override-build: |
      snapcraftctl build
      cp -R ../src/mods/ $SNAPCRAFT_PART_INSTALL
      cp ../src/COPYING $SNAPCRAFT_PART_INSTALL
    after: [ mod ]

  mod:
    plugin: dump
    source: https://github.com/flareteam/flare-game.git
    source-tag: v1.12
    stage:
      - -art_src/*
      - -tiled/*
